package com.cyrillrx.rpg.core.presentation.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color
import com.cyrillrx.rpg.settings.domain.Palette

data class AppPalette(val light: ColorScheme, val dark: ColorScheme)

/** Maps a domain [Palette] to its light/dark schemes. Exhaustive: a new palette must be listed here. */
fun Palette.toAppPalette(): AppPalette = when (this) {
    Palette.ARCANE -> AppPalette(ArcaneLightScheme, ArcaneDarkScheme)
    Palette.DRAGON -> AppPalette(DragonLightScheme, DragonDarkScheme)
    Palette.GROVE -> AppPalette(GroveLightScheme, GroveDarkScheme)
}

private val ArcaneLightScheme = lightColorScheme(
    primary = Color(0xFF512DA8),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFE9DDFF),
    onPrimaryContainer = Color(0xFF512DA8),
    inversePrimary = Color(0xFFD0BCFF),
    secondary = Color(0xFF625B71),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFE8DEF8),
    onSecondaryContainer = Color(0xFF1E192B),
    tertiary = Color(0xFF7A5900),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFDF9C),
    onTertiaryContainer = Color(0xFF261A00),
    error = ErrorLight,
    onError = OnErrorLight,
    errorContainer = ErrorContainerLight,
    onErrorContainer = OnErrorContainerLight,
    background = Color(0xFFFFFBFF),
    onBackground = Color(0xFF1C1B1E),
    surface = Color(0xFFFFFBFF),
    onSurface = Color(0xFF1C1B1E),
    surfaceVariant = Color(0xFFE7E0EB),
    onSurfaceVariant = Color(0xFF49454E),
    outline = Color(0xFF7A757F),
    outlineVariant = Color(0xFFCBC4CF),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF6F0F7),
    surfaceContainer = Color(0xFFF1EBF3),
    surfaceContainerHigh = Color(0xFFEBE5ED),
    surfaceContainerHighest = Color(0xFFE5E0E8),
    inverseSurface = Color(0xFF313033),
    inverseOnSurface = Color(0xFFF4EFF4),
    scrim = Color(0xFF000000),
    surfaceTint = Color(0xFF512DA8),
)

private val ArcaneDarkScheme = darkColorScheme(
    primary = Color(0xFFB69DF8),
    onPrimary = Color(0xFF381E72),
    primaryContainer = Color(0xFF4F378A),
    onPrimaryContainer = Color(0xFFB69DF8),
    inversePrimary = Color(0xFF512DA8),
    secondary = Color(0xFFD3C1EC),
    onSecondary = Color(0xFF382C4B),
    secondaryContainer = Color(0xFF4C4160),
    onSecondaryContainer = Color(0xFFEBDCFB),
    tertiary = Color(0xFFF5BD48),
    onTertiary = Color(0xFF402D00),
    tertiaryContainer = Color(0xFF5C4300),
    onTertiaryContainer = Color(0xFFFFDF9C),
    error = ErrorDark,
    onError = OnErrorDark,
    errorContainer = ErrorContainerDark,
    onErrorContainer = OnErrorContainerDark,
    background = Color(0xFF201D26),
    onBackground = Color(0xFFE8E2EA),
    surface = Color(0xFF201D26),
    onSurface = Color(0xFFE8E2EA),
    surfaceVariant = Color(0xFF4A4550),
    onSurfaceVariant = Color(0xFFCCC5D1),
    surfaceContainerLowest = Color(0xFF16131B),
    surfaceContainerLow = Color(0xFF2A2733),
    surfaceContainer = Color(0xFF302C39),
    surfaceContainerHigh = Color(0xFF3B3744),
    surfaceContainerHighest = Color(0xFF46424F),
    outline = Color(0xFF978F9D),
    outlineVariant = Color(0xFF4A4550),
    inverseSurface = Color(0xFFE8E2EA),
    inverseOnSurface = Color(0xFF313033),
    scrim = Color(0xFF000000),
    surfaceTint = Color(0xFFB69DF8),
)

private val DragonLightScheme = lightColorScheme(
    primary = Color(0xFFB3261E),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFDAD4),
    onPrimaryContainer = Color(0xFFB3261E),
    inversePrimary = Color(0xFFFFB4AB),
    secondary = Color(0xFF8F4E44),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFFFDBD3),
    onSecondaryContainer = Color(0xFF3A0906),
    tertiary = Color(0xFF7A5900),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFDF9C),
    onTertiaryContainer = Color(0xFF261A00),
    error = ErrorLight,
    onError = OnErrorLight,
    errorContainer = ErrorContainerLight,
    onErrorContainer = OnErrorContainerLight,
    background = Color(0xFFFFFDF6),
    onBackground = Color(0xFF24201A),
    surface = Color(0xFFFFFDF6),
    onSurface = Color(0xFF24201A),
    surfaceVariant = Color(0xFFEAE1CC),
    onSurfaceVariant = Color(0xFF4C4636),
    outline = Color(0xFF7E7458),
    outlineVariant = Color(0xFFCFC4A6),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFFBF5E6),
    surfaceContainer = Color(0xFFF5EDDA),
    surfaceContainerHigh = DndParchment,
    surfaceContainerHighest = Color(0xFFEADFC6),
    inverseSurface = Color(0xFF37322A),
    inverseOnSurface = Color(0xFFF7F0E2),
    scrim = Color(0xFF000000),
    surfaceTint = Color(0xFFB3261E),
)

private val DragonDarkScheme = darkColorScheme(
    primary = Color(0xFFFFB4AB),
    onPrimary = Color(0xFF690005),
    primaryContainer = Color(0xFF93000A),
    onPrimaryContainer = Color(0xFFFFDAD4),
    inversePrimary = Color(0xFFB3261E),
    secondary = Color(0xFFE7BDB6),
    onSecondary = Color(0xFF442925),
    secondaryContainer = Color(0xFF5D3F3B),
    onSecondaryContainer = Color(0xFFFFDBD3),
    tertiary = Color(0xFFF5BD48),
    onTertiary = Color(0xFF402D00),
    tertiaryContainer = Color(0xFF5C4300),
    onTertiaryContainer = Color(0xFFFFDF9C),
    error = ErrorDark,
    onError = OnErrorDark,
    errorContainer = ErrorContainerDark,
    onErrorContainer = OnErrorContainerDark,
    background = Color(0xFF1A1110),
    onBackground = Color(0xFFF1DEDB),
    surface = Color(0xFF1A1110),
    onSurface = Color(0xFFF1DEDB),
    surfaceVariant = Color(0xFF534341),
    onSurfaceVariant = Color(0xFFD8C2BE),
    outline = Color(0xFFA08C89),
    outlineVariant = Color(0xFF534341),
    surfaceContainerLowest = Color(0xFF140B0A),
    surfaceContainerLow = Color(0xFF231917),
    surfaceContainer = Color(0xFF271D1B),
    surfaceContainerHigh = Color(0xFF322825),
    surfaceContainerHighest = Color(0xFF3D3230),
    inverseSurface = Color(0xFFF1DEDB),
    inverseOnSurface = Color(0xFF362F2E),
    scrim = Color(0xFF000000),
    surfaceTint = Color(0xFFFFB4AB),
)

private val GroveLightScheme = lightColorScheme(
    primary = Color(0xFF386A20),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFB8F397),
    onPrimaryContainer = Color(0xFF072100),
    inversePrimary = Color(0xFF9DD67D),
    secondary = Color(0xFF55624C),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFD9E7CB),
    onSecondaryContainer = Color(0xFF131F0D),
    tertiary = Color(0xFF825500),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFDDB4),
    onTertiaryContainer = Color(0xFF291800),
    error = ErrorLight,
    onError = OnErrorLight,
    errorContainer = ErrorContainerLight,
    onErrorContainer = OnErrorContainerLight,
    background = Color(0xFFFFFDF6),
    onBackground = Color(0xFF24201A),
    surface = Color(0xFFFFFDF6),
    onSurface = Color(0xFF24201A),
    surfaceVariant = Color(0xFFEAE1CC),
    onSurfaceVariant = Color(0xFF4C4636),
    outline = Color(0xFF7E7458),
    outlineVariant = Color(0xFFCFC4A6),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFFBF5E6),
    surfaceContainer = Color(0xFFF5EDDA),
    surfaceContainerHigh = DndParchment,
    surfaceContainerHighest = Color(0xFFEADFC6),
    inverseSurface = Color(0xFF37322A),
    inverseOnSurface = Color(0xFFF7F0E2),
    scrim = Color(0xFF000000),
    surfaceTint = Color(0xFF386A20),
)

private val GroveDarkScheme = darkColorScheme(
    primary = Color(0xFF9DD67D),
    onPrimary = Color(0xFF0C3900),
    primaryContainer = Color(0xFF1F5200),
    onPrimaryContainer = Color(0xFFB8F397),
    inversePrimary = Color(0xFF386A20),
    secondary = Color(0xFFBDCBAF),
    onSecondary = Color(0xFF283420),
    secondaryContainer = Color(0xFF3E4A34),
    onSecondaryContainer = Color(0xFFD9E7CB),
    tertiary = Color(0xFFE9C18C),
    onTertiary = Color(0xFF452B00),
    tertiaryContainer = Color(0xFF624000),
    onTertiaryContainer = Color(0xFFFFDDB4),
    error = ErrorDark,
    onError = OnErrorDark,
    errorContainer = ErrorContainerDark,
    onErrorContainer = OnErrorContainerDark,
    background = Color(0xFF12140E),
    onBackground = Color(0xFFE2E3D9),
    surface = Color(0xFF12140E),
    onSurface = Color(0xFFE2E3D9),
    surfaceVariant = Color(0xFF43483D),
    onSurfaceVariant = Color(0xFFC3C8B8),
    outline = Color(0xFF8D9286),
    outlineVariant = Color(0xFF43483D),
    surfaceContainerLowest = Color(0xFF0D0F09),
    surfaceContainerLow = Color(0xFF1A1C16),
    surfaceContainer = Color(0xFF1E201A),
    surfaceContainerHigh = Color(0xFF282B24),
    surfaceContainerHighest = Color(0xFF33362E),
    inverseSurface = Color(0xFFE2E3D9),
    inverseOnSurface = Color(0xFF2F312A),
    scrim = Color(0xFF000000),
    surfaceTint = Color(0xFF9DD67D),
)
