[versions]
kotlin = "2.0.21"
ktlint = "11.5.1"
agp = "8.7.3"
compose-plugin = "1.7.0"
kotlinx-coroutines-core = "1.9.0"
kotlinx-serialization = "1.7.3"

#ktor = "3.0.0"
composeRuntime = "1.7.3"
sqlDelight = "2.0.2"

androidx-compose = "1.7.6"
androidx-appcompat = "1.7.0"
androidx-coreKtx = "1.15.0"
androidx-activity-compose = "1.10.0"
navigationCompose = "2.8.0-alpha10"

legacy-materialVersion = "1.12.0"

[libraries]
jetbrains-compose-navigation = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines-core" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines-core" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

jetbrains-lifecycle-runtime-compose = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "composeRuntime" }

#ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
#ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
#ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
#ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
#ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

sqldelight-runtime = { module = "app.cash.sqldelight:runtime", version.ref = "sqlDelight" }
sqldelight-android = { module = "app.cash.sqldelight:android-driver", version.ref = "sqlDelight" }
sqldelight-native = { module = "app.cash.sqldelight:native-driver", version.ref = "sqlDelight" }
sqldelight-jvm = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "sqlDelight" }


# Android Only
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-coreKtx" }
androidx-ui = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-compose" }
legacy-material = { module = "com.google.android.material:material", version.ref = "legacy-materialVersion" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }

sqldelight = { id = "app.cash.sqldelight", version.ref = "sqlDelight" }
