version: 2

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Europe/Paris"
    labels:
      - "dependencies"
      - "Android"
    open-pull-requests-limit: 4

  - package-ecosystem: "swift"
    directory: "/iosApp"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Europe/Paris"
    labels:
      - "dependencies"
      - "iOS"
    open-pull-requests-limit: 4
